### ISSUE TITLE
Question about configuring a location of generated resources for WebSharper client control

### ISSUE THREAD

**Issue by ArtemyB** [dotnet-websharper/aspnetmvc#2]
Tried to use this extension to embed a WS client-control to an ASP.NET app (was using WebSharper 4 so I've just recompiled this library with new version of WebSharper).
But ran into some errors in web-console, which says that included scripts have not been loaded -- there were no WS-generated scripts in `/scripts/WebSharper` folder.

Initially I put my control code in "WebSharper Library" project. So there were no generated scripts neither in `MyAspNetApp/Scripts/WebSharper` folder, nor in the `MyWebSharperLib/Scripts/WebSharper` folder.

Then I've changed "WebSharper Library" project type to "WebSharper Client-Server App" (just created a fresh one and put my control code in it). At this time scripts were generated, but in the `MyWebSharperApp/Scripts/WebSharper`, whereas in the `<head>` of the ASP.NET page all resources links use `Scripts/WebSharper` folder in the ASP.NET project. So it again can't locate the resources.

How can I make my control's resources being generated in ASP.NET project's `Scripts` folder instead of  WS project's one? Or, maybe, how can I change resources' (scripts') paths to their actual location's path?
And also why the scripts are not generated at all in case of "WebSharper Library" project?

**Comment by Tarmil** [comment]
You need to turn your ASP.NET project itself into a WebSharper client-server app. For this, you simply need to add `WebSharper.CSharp` as a NuGet dependency (for WS 4; `WebSharper` for WS 3) and add `<WebSharperProject>Website</WebSharperProject>` in a PropertyGroup of the project file.

**Comment by ArtemyB** [comment]
@Tarmil  did not suspect, that the ASP.NET project should have this property. Thank you! :slightly_smiling_face:  Now the scripts are generated in the ASP.NET project's `Scripts/WebSharper` folder. I've also noticed that if the control uses, for example, UI.Next and WebSharper.Forms, these assemblies should also be referenced by ASP.NET project, otherwise the errors about missing scripts appear and control still doesn't render. However when I've referenced the assemblies, another error appeared -- now at the compile time. Here it is:

`D:\Prog\Web\WebSharper.AspNetMvc.Test\packages\WebSharper.UI.Next.4.0.13.126\build\WebSharper.UI.Next.targets(32,5): error MSB4062: The "WebSharper.UI.Next.CSharp.Templating.Build.WebSharperUINextCSharpGeneratorTask" task could not be loaded from the assembly D:\Prog\Web\WebSharper.AspNetMvc.Test\packages\WebSharper.UI.Next.4.0.13.126\build\/../tools/WebSharper.UI.Next.CSharp.Templating.Build.dll. Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Не удается найти указанный файл. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

I have bindingRedirect for FSharp.Core in my Web.config: `<bindingRedirect oldVersion="0.0.0.0-4.4.1.0" newVersion="4.4.1.0" />`, so I don't really understand what the error is about. Do you know what the problem may be?

**Comment by ArtemyB** [comment]
I've tried to build the project again, but now in the right way -- using `build.cmd` script (previously I done this using MsBuild with Paket for dependencies -- as for usual VS project). After that the problem described above has disappeared, and now my client control successfully works in the ASP.NET MVC project.

P.S. And the WebSharper version used is 4.1 now 😃

**Comment by V0d01ey** [comment]
@ArtemyB  Can you please give that `build.cmd` script, so that others could resolve this issue too?

**Comment by ArtemyB** [comment]
@V0d01ey that was [`build.cmd` from this repo](https://github.com/dotnet-websharper/aspnetmvc/blob/master/build.cmd), I used it without any changes. The only change could be needed is new `NuGet.exe` (see #4 ), which can be downloaded from [here](https://www.nuget.org/downloads). After downloading the nuget's .exe file rename it to `NuGet.exe` and put it to `/tools/NuGet/` (with replacing, of course).
