### ISSUE TITLE
WebSharper 4 support

### ISSUE THREAD

**Issue by ArtemyB** [dotnet-websharper/aspnetmvc#3]
Recently I've recompiled this project using WebSharper 4 as a dependency and it seems okay. At least, there is no compilation errors. Also tried using WS client control in ASP.NET MVC application -- necessary resource imports was added to the `<head>`, also a `<div>` for control was added. So I hope updating the dependencies is enough to make this library work with WebSharper 4 projects.

P.S. : I haven't tested using sitelets and RPC in ASP.NET MVC project yet.

**Comment by Tarmil** [comment]
Now released for WebSharper 4.2.
