### ISSUE TITLE
Irrelevant NuGet.exe?

### ISSUE THREAD

**Issue by ArtemyB** [dotnet-websharper/aspnetmvc#4]
When I was trying to build this project via "build.cmd" script, there was an error that packages cannot be found. However when I've downloaded newer version of NuGet distributions from [here](https://www.nuget.org/downloads) (v4.4.1 in my case) and replaced `NuGet.exe` in `tools/NuGet` folder with this downloaded one (I've changed its' name to the `NuGet.exe` of course), the project was built successfully.

**Comment by Tarmil** [comment]
This is obsoleted by the switch to Paket.
