### ISSUE TITLE
Cannot build the project (dotnet-websharper/aspnetmvc)

### ISSUE THREAD

**Issue by ArtemyB** [dotnet-websharper/aspnetmvc#6]
Wanted to update WebSharper.AspNetMvc package (there is an old one in the NuGet gallery - 3.6.10.2 - which does not work with WebSharper 4.x, so to use WebSharper with my ASP.NET MVC project I am using local build, which is working with WS 4.1, but unfortunately does not work with WS 4.2).

So when I run the `build.cmd` script now, the following error occurs:
```
IntelliFactory.Build.NuGetResolver: [warn] Could not resolve package: WebSharper
System.Exception: Failed to get the version from WebSharper
   в <StartupCode$IntelliFactory-Build>.$BuildTool.VersionFrom@118.Invoke(String message)
   в <StartupCode$FSI_0002>.$FSI_0002.main@() в D:\Prog\F#\Web\WebSharper.AspNetMvc\aspnetmvc\build.fsx:line 4
Stopped due to error
```

Would be very cool to solve this problem to be able to use WS 4.2 with my ASP.NET MVC project. 😄

**Comment by ArtemyB** [comment]
Have tried using NuGet-source with API v2 instead of v3 and it helps a little -- build proceeds a little further, but another error occurs:
```
IntelliFactory.Build.PackageVersionTool: [info] 4.2 --> 4.2.1
System.Exception: Could not locate WsFsc.exe - consider setting WebSharperHome
   в <StartupCode$IntelliFactory-Build>.$WebSharper4.clo@133-44.Invoke(String message)
   в IntelliFactory.Build.WebSharper4Utility.ExecuteWebSharper(ResolvedReferences rr, IEnumerable`1 args, FSharpOption`1 pass)
   в <StartupCode$IntelliFactory-Build>.$WebSharper4.clo@423-51.Invoke(IEnumerable`1 fscArgs)
   в IntelliFactory.Build.WebSharper4Project.build()
   в <StartupCode$IntelliFactory-Build>.$Solutions.Build@38.Invoke(AppDomain dom)
   в IntelliFactory.Build.Solution.WithDomain[T](FSharpFunc`2 f)
   в IntelliFactory.Build.BuildTool.Dispatch(Solution sln)
   в <StartupCode$FSI_0002>.$FSI_0002.main@() в D:\Prog\F#\Web\WebSharper.AspNetMvc\aspnetmvc\build.fsx:line 10
Stopped due to error
```

**Comment by Tarmil** [comment]
Right, this project hasn't been updated to use FAKE+Paket. I can do that now.

**Comment by ArtemyB** [comment]
@Tarmil that would be great! Because I couldn't figure out how to set this WebSharperHome from the build script by myself. And anyway it seems not relevant due to the new build process via FAKE + Paket.

**Comment by Tarmil** [comment]
This is now done, and released on NuGet as WebSharper.AspNetMvc 4.2.0.1.

**Comment by ArtemyB** [comment]
Perfect, thank you!
